[package]
name = "apple-notes-exporter-rs"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "apple-notes-exporter"
path = "src/main.rs"

[dependencies]
clap = { version = "4.5.20", features = ["derive"] }
